---
name: inspec-exec-win

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Install Inspec upstream packages
        run: |
          curl -O https://packages.chef.io/files/current/inspec/5.12.2/windows/2022/inspec-5.12.2-1-x64.msi
          msiexec /quiet /passive /i inspec-5.12.2-1-x64.msi /qn /norestart /le c:\inspec-msi.log
          type c:\inspec-msi.log
      - name: Check Inspec
        run: |
          dir c:\
          dir c:\opscode
          dir c:\opscode\inspec\bin
          mkdir C:\chef\accepted_licenses
          echo > C:\chef\accepted_licenses\inspec
        continue-on-error: true
      - name: Run Inspec exec
        run: |
          c:\opscode\inspec\bin\inspec.bat exec .
