---
name: inspec-exec-linux

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Install Inspec upstream packages
        run: |
          curl -O https://packages.chef.io/files/stable/inspec/5.12.2/ubuntu/20.04/inspec_5.12.2-1_amd64.deb
          sudo apt-get install -y ./inspec_5.12.2-1_amd64.deb
          sudo mkdir -p /etc/chef/accepted_licenses
          sudo touch /etc/chef/accepted_licenses/inspec
      - name: Environment
        run: |
          set -x
          env
          which inspec || true
      - name: Run Inspec exec
        run: inspec exec .
        continue-on-error: true
      # https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually
      - name: Install MDE without onboarding
        run: |
          set -x
          sudo apt-get install -y curl libplist-utils gpg apt-transport-https
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl -o microsoft.list https://packages.microsoft.com/config/ubuntu/20.04/prod.list
          cat microsoft.list
          sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install -y mdatp
          mdatp health
          mdatp connectivity test
          mdatp definitions update
      - name: Misc
        run: |
          ls -lA /opt/microsoft/mdatp/conf/
          ls -lA /var/log/microsoft/mdatp/
          sudo chmod 644 /opt/microsoft/mdatp/conf/mdatp.rules
      - name: Run Inspec exec
        run: inspec exec --input-file input-test.yml .
