---
name: inspec-exec-win

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - ruby-version: '3.0'
            experimental: false

    steps:
      - uses: actions/checkout@v2
      - name: Install Inspec upstream packages
        run: |
          curl -O https://packages.chef.io/files/current/inspec/5.12.2/windows/2022/inspec-5.12.2-1-x64.msi
          msiexec /i inspec-5.12.2-1-x64.msi /qn /norestart
      - name: Run Inspec exec
        run: c:\opscode\inspec\bin\inspec.bat exec .
        continue-on-error: true
